- hosts: localhost
  tasks:
 

      
    - name: Získaj konfig z adresy
      get_url:
        url: https://raw.githubusercontent.com/marsur/ansible_pull/refs/heads/main/cronjobs.txt
        dest: /var/spool/cron/root

